openapi: 3.0.0
info:
  title: Test API
  version: 2.0.1
paths:
  /Allusers:
    get:
      summary: Get users
      parameters:
        - name: page
          in: query
          required: true
          schema:
            type: string
        - name: limit
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                required:
                  - id
                  
                properties:
                  
                  name:
                    type: string
                  email:
                    type: string
                  age:
                    type: integer
  /orders/{id}:
   
        '404':
          description: Not found
