openapi: 3.1.0
info:
  title: Test API
  version: 4.0.0 
paths:
  /breaking-test: 
    get:
      summary: This must trigger scan 19
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                required:
                  - status
                properties:
                  status:
                    type: string
